# server/Dockerfile
FROM oven/bun:1.0.25
WORKDIR /app

# Ajustar os caminhos para copiar da raiz
COPY server/package.json server/bun.lock* ./
RUN bun install

# Copiar o resto
COPY shared ./shared
COPY server ./server

EXPOSE 3000
CMD ["bun", "run", "server/index.ts"]