# docker-compose.yml for VPS deployment
#
# Copy this file to your server along with the project source,
# then run `docker compose up -d` to start the stack.

services:
  postgres:
    image: postgres:15
    container_name: geo-map-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geo-map-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: geo-map-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      PORT: 3000
      SESSION_SECRET: ${SESSION_SECRET}
      LOCAL_CLIENT_PORT: ${LOCAL_CLIENT_PORT}
      CORS_ORIGIN: ${CORS_ORIGIN}
      CORS_ORIGIN_2: ${CORS_ORIGIN_2}
      VIACEP_API_URL: ${VIACEP_API_URL}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - geo-map-net
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
      args:
        NODE_ENV: production
    container_name: geo-map-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      VITE_API_URL: ${VITE_API_URL}
      VITE_API_PROXY_TARGET: ${VITE_API_PROXY_TARGET}
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
    depends_on:
      - backend
    networks:
      - geo-map-net
    ports:
      - "5173:5173"

volumes:
  postgres_data:

networks:
  geo-map-net:
    driver: bridge
