# docker-compose.yml for VPS deployment
#
# Copy this file to your server along with the project source,
# then run `docker compose up -d` to start the stack.

services:
  postgres:
    image: postgres:15
    container_name: geo-map-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-geomap}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-geomap}
      POSTGRES_DB: ${POSTGRES_DB:-geomap}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geo-map-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-geomap} -d ${POSTGRES_DB:-geomap}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: geo-map-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://geomap:geomap@postgres:5432/geomap}
      NODE_ENV: production
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - geo-map-net
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        NODE_ENV: production
    container_name: geo-map-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      VITE_API_URL: ${VITE_API_URL:-http://backend:3000}
      VITE_API_PROXY_TARGET: ${VITE_API_PROXY_TARGET:-http://backend:3000}
    depends_on:
      - backend
    networks:
      - geo-map-net
    ports:
      - "5173:5173"

volumes:
  postgres_data:

networks:
  geo-map-net:
    driver: bridge
