CREATE TABLE "audit_log" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer,
	"action" varchar(50) NOT NULL,
	"table_name" varchar(50) NOT NULL,
	"record_id" integer,
	"old_values" jsonb,
	"new_values" jsonb,
	"ip_address" varchar(45),
	"user_agent" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "equipamentos_sociais" (
	"id" serial PRIMARY KEY NOT NULL,
	"nome" varchar(255) NOT NULL,
	"tipo" varchar(100) NOT NULL,
	"endereco" text NOT NULL,
	"cep" varchar(10) NOT NULL,
	"latitude" double precision,
	"longitude" double precision,
	"telefone" varchar(20),
	"email" varchar(255),
	"horario_funcionamento" text,
	"servicos" text[],
	"ativo" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "geocoding_cache" (
	"id" serial PRIMARY KEY NOT NULL,
	"address_hash" varchar(64) NOT NULL,
	"address" text NOT NULL,
	"cep" varchar(10) NOT NULL,
	"latitude" double precision,
	"longitude" double precision,
	"source" varchar(20) NOT NULL,
	"error_message" text,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "geocoding_cache_address_hash_unique" UNIQUE("address_hash")
);
--> statement-breakpoint
CREATE TABLE "ongs" (
	"id" serial PRIMARY KEY NOT NULL,
	"nome" varchar(255) NOT NULL,
	"endereco" text NOT NULL,
	"cep" varchar(10) NOT NULL,
	"latitude" double precision,
	"longitude" double precision,
	"telefone" varchar(20),
	"email" varchar(255),
	"site" varchar(255),
	"tipo" varchar(100),
	"areas_atuacao" text[],
	"horario_funcionamento" varchar(100),
	"servicos" text[],
	"responsavel" varchar(255),
	"place_id" varchar(255),
	"google_rating" double precision,
	"google_photo_url" varchar(500),
	"ativo" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "orientacoes_encaminhamento" (
	"id" serial PRIMARY KEY NOT NULL,
	"paciente_id" integer NOT NULL,
	"orientacao_anterior" text,
	"proxima_orientacao" text NOT NULL,
	"observacoes_seguimento" text,
	"seguiu_orientacao" boolean,
	"data_orientacao" timestamp DEFAULT now(),
	"usuario_id" integer,
	"ativo" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "pacientes" (
	"id" serial PRIMARY KEY NOT NULL,
	"local_atendimento" varchar(255),
	"data_atendimento" timestamp,
	"equipe" varchar(100) DEFAULT 'Samambaia - DF',
	"nome" varchar(255) NOT NULL,
	"nome_social" varchar(255),
	"nome_mae" varchar(255),
	"nome_pai" varchar(255),
	"naturalidade" varchar(255),
	"data_nascimento" timestamp,
	"idade" integer,
	"cns_ou_cpf" varchar(20),
	"endereco" text NOT NULL,
	"cep" varchar(10) NOT NULL,
	"latitude" double precision,
	"longitude" double precision,
	"telefone" varchar(20),
	"identidade_genero" varchar(50),
	"cor_raca" varchar(50),
	"orientacao_sexual" varchar(50),
	"internacao" boolean,
	"ideacao_suicida" boolean,
	"tentativa_suicidio" boolean,
	"pressao_arterial" varchar(20),
	"frequencia_cardiaca" varchar(10),
	"fc_classificacao" varchar(20),
	"frequencia_respiratoria" varchar(10),
	"fr_classificacao" varchar(20),
	"temperatura" varchar(10),
	"peso" varchar(10),
	"glicemia_capilar" varchar(10),
	"teste_gravidez" varchar(20),
	"teste_sifilis" boolean,
	"teste_hep_b" boolean,
	"teste_hep_c" boolean,
	"teste_hiv" boolean,
	"uso_alcool" boolean,
	"uso_maconha" boolean,
	"uso_cocaina" boolean,
	"uso_crack" boolean,
	"uso_sinteticos" boolean,
	"uso_volateis" boolean,
	"dm_familiar" boolean,
	"ha_familiar" boolean,
	"avc_familiar" boolean,
	"iam_familiar" boolean,
	"ca_familiar" boolean,
	"depressao_familiar" boolean,
	"ansiedade_familiar" boolean,
	"esquizo_familiar" boolean,
	"bipolar_familiar" boolean,
	"alcool_familiar" boolean,
	"drogas_familiar" boolean,
	"dm" boolean,
	"ha" boolean,
	"avc" boolean,
	"iam" boolean,
	"ca" boolean,
	"depressao" boolean,
	"ansiedade" boolean,
	"esquizo" boolean,
	"bipolar" boolean,
	"alcoolismo" boolean,
	"asma" boolean,
	"medicacao_em_uso" text,
	"kit_odonto" boolean,
	"kit_higiene" boolean,
	"vacina" boolean,
	"coleta_sangue" boolean,
	"adm_medicacao" boolean,
	"medicacao_administrada" text,
	"estado_geral" varchar(100),
	"orientacao" varchar(100),
	"consciencia" varchar(100),
	"hidratacao" varchar(100),
	"nutricao" varchar(100),
	"coloracao" varchar(100),
	"facies" varchar(20),
	"facies_descricao" text,
	"pulsos_presenca" varchar(20),
	"pulsos_simetria" varchar(20),
	"mmii_perfusao" varchar(30),
	"mmii_tvp" varchar(30),
	"linfonodomegalias" varchar(10),
	"linfonodomegalias_descricao" text,
	"tvp_panturrilhas" varchar(20),
	"tvp_sinal_homans" varchar(20),
	"edema_facies" boolean,
	"edema_maos" boolean,
	"edema_pes" boolean,
	"edema_generalizado" boolean,
	"abdomen_tipo" varchar(20),
	"abdomen_massas" varchar(30),
	"abdomen_hernia_umbilical" boolean,
	"abdomen_hernia_inguinal" boolean,
	"abdomen_retracoes" boolean,
	"abdomen_circulacao_colateral" varchar(20),
	"abdomen_peristalse" varchar(30),
	"abdomen_lesoes_cutaneas" text,
	"abdomen_ruidos_hidroaereos" varchar(10),
	"abdomen_sopros" varchar(10),
	"abdomen_distendido" varchar(10),
	"abdomen_dor" varchar(20),
	"abdomen_sinal_murphy" varchar(10),
	"abdomen_sinal_blumberg" varchar(10),
	"abdomen_sinal_giordano" varchar(10),
	"abdomen_visceromegalias" varchar(10),
	"condicoes_saude" text[],
	"ubs_mais_proxima_id" integer,
	"distancia_ubs" double precision,
	"evolucao" text,
	"observacoes" text,
	"ultimo_atendimento" timestamp,
	"proximo_atendimento" timestamp,
	"ativo" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ubs" (
	"id" serial PRIMARY KEY NOT NULL,
	"nome" varchar(255) NOT NULL,
	"endereco" text NOT NULL,
	"cep" varchar(10) NOT NULL,
	"latitude" double precision,
	"longitude" double precision,
	"telefone" varchar(20),
	"email" varchar(255),
	"horario_funcionamento" text,
	"especialidades" text[],
	"gestor" varchar(255),
	"place_id" varchar(255),
	"google_rating" double precision,
	"google_photo_url" varchar(500),
	"ativo" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" varchar(50) NOT NULL,
	"email" varchar(255) NOT NULL,
	"password" text NOT NULL,
	"email_verified" boolean DEFAULT false,
	"verification_token" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orientacoes_encaminhamento" ADD CONSTRAINT "orientacoes_encaminhamento_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orientacoes_encaminhamento" ADD CONSTRAINT "orientacoes_encaminhamento_usuario_id_users_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pacientes" ADD CONSTRAINT "pacientes_ubs_mais_proxima_id_ubs_id_fk" FOREIGN KEY ("ubs_mais_proxima_id") REFERENCES "public"."ubs"("id") ON DELETE no action ON UPDATE no action;
